import 'package:flutter/material.dart';
import '../../domain/ui_trend.dart';

class StyleGuideGenerator {
  static String generateMarkdown(UITrend trend) {
    final buffer = StringBuffer();
    buffer.writeln('# 💎 AI-Agent Optimized Style Guide: ${trend.name}');
    buffer.writeln('\n> ${trend.tagline}\n');
    
    buffer.writeln('## 📌 Trend Overview');
    buffer.writeln(trend.description);
    
    buffer.writeln('\n## 🎨 Visual Rules & Tokens');
    buffer.writeln('- **Primary Accent**: `#${trend.accentColor.toARGB32().toRadixString(16).padLeft(8, '0').substring(2).toUpperCase()}`');
    buffer.writeln('- **Secondary Accent**: `#${trend.secondaryAccent.toARGB32().toRadixString(16).padLeft(8, '0').substring(2).toUpperCase()}`');
    buffer.writeln('- **Background**: `#${trend.bgColor.toARGB32().toRadixString(16).padLeft(8, '0').substring(2).toUpperCase()}`');
    buffer.writeln('- **Surface**: `#${trend.surfaceColor.toARGB32().toRadixString(16).padLeft(8, '0').substring(2).toUpperCase()}`');
    buffer.writeln('- **Typography**: Focus on clarity and high contrast.');
    
    buffer.writeln('\n### Key Visual Characteristics:');
    for (var kw in trend.keywords) {
      buffer.writeln('- $kw');
    }

    buffer.writeln('\n## 🤖 AI Agent Implementation Rules');
    buffer.writeln('When generating components for this specific aesthetic, you MUST follow these constraints:');
    
    _addTrendSpecificRules(buffer, trend.id);

    buffer.writeln('\n## 💻 Core Component Code Snippets');
    buffer.writeln('For Flutter implementation, use these patterns:');
    
    _addTrendSpecificCode(buffer, trend);
    
    buffer.writeln('\n---');
    buffer.writeln('Generated by **HomelessArchitect UI Lab** - 2026');
    buffer.writeln('Optimized for Claude 3.5 Sonnet, GPT-4, and Gemini 1.5 Pro Agents.');

    return buffer.toString();
  }

  static void _addTrendSpecificRules(StringBuffer buffer, String id) {
    if (id == 'glassmorphism') {
      buffer.writeln('1. ALWAYS wrap containers with `BackdropFilter` and `ImageFilter.blur`.');
      buffer.writeln('2. Surface alpha should be between 0.1 and 0.25 (e.g., `Colors.white.withOpacity(0.15)`).');
      buffer.writeln('3. Use a thin 1.0 or 1.5 border with slightly higher opacity than the surface.');
      buffer.writeln('4. Use multi-stop linear gradients for backgrounds (45-degree angles).');
    } else if (id == 'tokyo_night') {
      buffer.writeln('1. Backgrounds MUST be deep dark blues or blacks (`#1a1b26`).');
      buffer.writeln('2. Use neon glow effects via `BoxShadow` with blur radius > 20.');
      buffer.writeln('3. Typography should be high-contrast (pure white) with subtle letter-spacing.');
      buffer.writeln('4. Use Cyan and Magenta as dual-accent indicators (e.g., success/error).');
    } else if (id == 'neo_clean') {
      buffer.writeln('1. Use `BorderRadius.zero` for all interactive elements.');
      buffer.writeln('2. Borders MUST be visible, black, and at least 2.5px thick.');
      buffer.writeln('3. Use "Hard Shadows" (`BoxShadow` with 0 blur and 4px offset).');
      buffer.writeln('4. Layouts should follow a strict grid with intentional whitespace.');
    } else if (id == 'neumorphism') {
      buffer.writeln('1. Elements MUST match the background color perfectly for the "extrusion" effect.');
      buffer.writeln('2. Use two shadows: one lighter than the background (Top-Left) and one darker (Bottom-Right).');
      buffer.writeln('3. Use `Offset(-5, -5)` for light and `Offset(5, 5)` for dark shadows.');
    } else if (id == 'lumine_glow') {
      buffer.writeln('1. Use orange/amber back-glows on primary buttons.');
      buffer.writeln('2. Cards should have "Light Leaks" at the top corners using subtle gradients.');
      buffer.writeln('3. Text should have a very soft `Shadow` to simulate light radiation.');
    } else if (id == 'holo_glass') {
      buffer.writeln('1. Iridescence is key: use linear gradients with at least 3-4 vibrant colors for borders.');
      buffer.writeln('2. Simulate chromatic aberration with offset colored shadows (red/blue).');
      buffer.writeln('3. Use extremely glossy surfaces (alpha 0.35+).');
    } else if (id == 'mono_archive') {
      buffer.writeln('1. Use "Dossier" tabs at the top of cards.');
      buffer.writeln('2. Dot patterns or grid backgrounds are required for transparency indicators.');
      buffer.writeln('3. Use monospaced fonts for technical data points.');
    } else if (id == 'tactile_industrial') {
      buffer.writeln('1. Use brushed metal textures (simulated via gradients).');
      buffer.writeln('2. Buttons should appear extruded or recessed with "cliqueable" depth.');
      buffer.writeln('3. Primary action colors must be industrial orange or warning yellow.');
    }
  }

  static void _addTrendSpecificCode(StringBuffer buffer, UITrend trend) {
    buffer.writeln('\n### Primary Container (${trend.name})\n');
    buffer.writeln('```dart');
    
    if (trend.id == 'glassmorphism') {
      buffer.writeln('''
// Glass Card with Blur
ClipRRect(
  borderRadius: BorderRadius.circular(20),
  child: BackdropFilter(
    filter: ImageFilter.blur(sigmaX: 12, sigmaY: 12),
    child: Container(
      decoration: BoxDecoration(
        color: Colors.white.withOpacity(0.15),
        border: Border.all(color: Colors.white.withOpacity(0.2)),
        borderRadius: BorderRadius.circular(20),
      ),
      padding: EdgeInsets.all(24),
      child: content,
    ),
  ),
)''');
    } else if (trend.id == 'tokyo_night') {
      buffer.writeln('''
// Neon Glow Card
Container(
  decoration: BoxDecoration(
    color: Color(0xFF24283b),
    borderRadius: BorderRadius.circular(12),
    border: Border.all(color: Color(0xFFff007c).withOpacity(0.3)),
    boxShadow: [
      BoxShadow(
        color: Color(0xFFff007c).withOpacity(0.1),
        blurRadius: 20,
        spreadRadius: 2,
      ),
    ],
  ),
  child: content,
)''');
    } else if (trend.id == 'neo_clean') {
      buffer.writeln('''
// Neo-Brutalist Card
Container(
  decoration: BoxDecoration(
    color: Colors.white,
    border: Border.all(color: Colors.black, width: 3),
    boxShadow: [
      BoxShadow(
        color: Colors.black,
        offset: Offset(4, 4),
        blurRadius: 0,
      ),
    ],
  ),
  child: content,
)''');
    } else {
      buffer.writeln('''
Container(
  decoration: BoxDecoration(
    color: ${trend.surfaceColor == Colors.white ? 'Colors.white' : 'Color(0x${trend.surfaceColor.toARGB32().toRadixString(16).toUpperCase()})'},
    borderRadius: BorderRadius.circular(16),
  ),
  child: content,
)''');
    }
    buffer.writeln('```');
  }
}
